### ISSUE TITLE
Should `match` assignment in `find` occur earlier?

### ISSUE THREAD

**Issue by wlewis-formative** [marcocesarato/dotenv-mono#146]
Given the following project structure (a root-level _.env_ file and a _.env_ file within a _src_ directory; see this [repo](https://github.com/wlewis-formative/dotenv-mono-mre)):

```
.env
src
 |- .env
 |- index.js
```

where the contents of the two .env files are as follows:

```env
# .env
VALUE=outer

# src/.env
VALUE=inner
```

I would expect the following behavior from this JavaScript file:

```javascript
// src/index.js
require("dotenv-mono").load();
console.log("cwd is", process.cwd());
console.log("process.env.VALUE is", process.env.VALUE);
```

1. When executed from the project's root directory, I would expect:

```shell
$ node src/index.js
cwd is .../<project-root-dir>
process.env.VALUE is outer
                     ^^^^^
```

2. When executed from the _src_ directory, I would expect:

```shell
$ node index.js
cwd is .../<project-root-dir>/src
process.env.VALUE is inner
                     ^^^^^
```

However, in both cases the value of the `VALUE` environment variable is `outer`. That is, even when the program is executed from within the _src_ directory, the root-level _.env_ file is used.

🤔 Am I misunderstanding the documentation on this point?

> Starting from the current process directory, this package finds the first file that matches the best filepath and filename criteria with the highest priority. The greater the depth of the up folder, the lesser its priority.

I wonder if [this check](https://github.com/marcocesarato/dotenv-mono/blob/de47d3fa878d56559d678b1a426702cbd996532c/src/index.ts#L414) needs to be swapped with the line before it. If that's the case, I can open a PR with the change.

**Comment by marcocesarato** [comment]
Hi, thanks for bringing this up! You're absolutely right about the behavior described. It seems like there might indeed be an issue with the code as it's not behaving as expected. Your understanding of the documentation seems spot on.

Swapping the check as you suggested sounds like a promising solution. If you're up for it, opening a PR with that change would be fantastic. Let's see if that resolves the discrepancy in behavior. Thanks again for your attention to detail!

**Comment by wlewis-formative** [comment]
Thanks @marcocesarato ! Opened #147 to address this. Appreciate all your work on this package 🙏
